=== tjwoodall/self-assessment-biss-api/resources/public/api/conf/3.0/schemas/retrieveBiss/def1/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve a Business Income Source Summary Response",
  "description": "Retrieve a Business Income Source Summary Response",
  "type": "object",
  "properties": {
    "total": {
      "type": "object",
      "description": "Object of total values.",
      "properties": {
        "income": {
          "description": "The total income for the income source. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 100.00,
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        },
        "expenses": {
          "description": "The total expenses for the income source. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 50.00,
          "minimum": -99999999999.99,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        },
        "additions": {
          "description": "The total additions to net profit (or deduction to net loss). The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 5.00,
          "minimum": -99999999999.99,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        },
        "deductions": {
          "description": "The total deductions to net loss (or addition to net profit). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 60.00,
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        },
        "accountingAdjustments": {
          "description": "Adjustment for change of accounting practice, for example, cash basis to accrual accounting. The value must be between -99999999999.99 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": -30.00,
          "minimum": -99999999999.99,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        }
      },
      "required": [
        "income",
        "expenses"
      ]
    },
    "profit": {
      "type": "object",
      "description": "Object of profit values.",
      "properties": {
        "net": {
          "description": "The net profit of income source. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 20.00,
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        },
        "taxable": {
          "description": "The taxable net profit of the income source. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 0.00,
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        },
        "adjusted": {
          "description": "Profit including disallowable expenses and deducting non‑taxable income, before claiming capital allowances or making any further tax adjustments. The value must be between 0 and 99999999999.99 up to 2 decimal places. This field will only be returned for tax year 2025-26 and onwards.",
          "type": "number",
          "example": 30.00,
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        }
      },
      "required": [
        "net",
        "taxable"
      ]
    },
    "loss": {
      "type": "object",
      "description": "Object of loss values.",
      "properties": {
        "net": {
          "description": "The net loss of income source. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 0.00,
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        },
        "taxable": {
          "description": "The taxable net loss of the income source. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 35.00,
          "minimum": 0,
          "maximum": 99999999999.99,
          "multipleOf": 0.01
        }
        
      },
      "required": [
        "net",
        "taxable"
      ]
    },
    
    "outstandingBusinessIncome": {
      "description": "Any other business income not included in other fields. The value must be between 0 and 99999999999.99 up to 2 decimal places. This field will only be returned for tax year 2025-26 and onwards.",
      "type": "number",
      "example": 30.00,
      "minimum": 0,
      "maximum": 99999999999.99,
      "multipleOf": 0.01
    }
  },
  "required": [
    "total",
    "profit",
    "loss"
  ]
}

=== tjwoodall/self-assessment-biss-api/resources/public/api/conf/3.0/examples/retrieveBiss/def1/responseTY2526Onwards.json
{
  "total": {
    "income": 100.35,
    "expenses": 50.01,
    "additions": 575.71,
    "deductions": 60.01,
    "accountingAdjustments": -30.01
  },
  "profit": {
    "net": 20.20,
    "taxable": 35.55,
    "adjusted": 30.01
  },
  "loss": {
    "net": 0.01,
    "taxable": 35.10
  },
  "outstandingBusinessIncome": 35.01
}
